# coding: utf-8

"""
    Test App APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
    Modified to add test stubs for testing the service APIs
"""


from __future__ import absolute_import
from __future__ import print_function

import unittest
import sys
from pprint import pprint
import json

"""
  Assumes that the service client code is extrated to this 'test' directory. If a different
  directory, then you need to modify the path appropriately.
"""
sys.path.append('./test/python-client')

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException

class TestApi(unittest.TestCase):
    """APIs unit tests"""

    def setUp(self):
        self.visitor_a = {}
        self.visitor_b = {}
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

        vis1 = swagger_client.Visitor(name='Brad Topol') # Visitor | The visitor to add.
        vis2 = swagger_client.Visitor(name='Henry Nash') # Visitor | The visitor to add.
        try:
            self.visitor_a = self.api.visitors_post(visitor=vis1)
            self.visitor_b = self.api.visitors_post(visitor=vis2)
        except ApiException as e:
            self.fail("Exception when calling Api->visitors_post: %s\n" % e)

    def tearDown(self):
         try:
             self.api.visitors_id_delete(self.visitor_a.id)
             self.api.visitors_id_delete(self.visitor_b.id)
             visitors = self.api.visitors_get()
             visitors_compare = []
             self.assertListEqual(visitors_compare, visitors, 'All visitors should be deleted')
         except ApiException as e:
             self.fail("Exception when calling Api->visitors_id_delete: %s\n" % e)

    def test_visitors_id_get(self):
         try:
             visitor = self.api.visitors_id_get(self.visitor_a.id)
             self.assertEqual(self.visitor_a.name, visitor.name, 'Visitor not retrieved as expected')
             self.assertEqual(self.visitor_a.id, visitor.id, 'Visitor not retrieved as expected')
         except ApiException as e:
             self.fail("Exception when calling Api->visitors_id_get: %s\n" % e)

    def test_visitors_get(self):
         try:
             visitors = self.api.visitors_get()
             visitors_compare = []
             visitors_compare.append(self.visitor_a)
             visitors_compare.append(self.visitor_b)
             self.assertListEqual(visitors_compare, visitors, 'All visitors not retrieved as expected')
         except ApiException as e:
             self.fail("Exception when calling Api->visitors_get: %s\n" % e)

    def test_visitors_post_duplicate(self):
         try:
             visitor = swagger_client.Visitor(name='Brad Topol') 
             self.api.visitors_post(visitor=visitor)
             self.fail('Visitor should not be added as it is a duplicate')
         except ApiException as e:
             self.assertEqual(409, e.status, ("Exception when calling Api->visitors_post: %s\n" % e))

if __name__ == '__main__':
    unittest.main()
